### ISSUE TITLE
Can't run it on Sabaki in windows

### ISSUE THREAD

**Issue by GLad-operating-system** [CGLemon/pyDLGO#1]
The situation is below
![1](https://user-images.githubusercontent.com/55128486/157078888-131a954a-e74f-43b7-a935-842df4911e6a.png)

**Comment by GLad-operating-system** [comment]
I tried to packet dlgo.py to be dlgo.exe with pyinstaller and it works

**Comment by CGLemon** [comment]
To be honest, I have no Windows environment. I have no idea how to run it on Windows. Look like you find a way to run it. [Here](https://superuser.com/questions/378477/making-usr-bin-env-python-work-on-windows) is another way I found.

I need the tutorial document for Windows user. Could you help me to write it and pull a request? Thanks!

**Comment by GLad-operating-system** [comment]
> To be honest, I have no Windows environment. I have no idea how to run it on Windows. Look like you find a way to run it. [Here](https://superuser.com/questions/378477/making-usr-bin-env-python-work-on-windows) is another way I found.
> 
> I need the tutorial document for Windows user. Could you help me to write it and pull a request? Thanks!

我很樂意幫忙，但還是有些問題，你的方法可以讓python文件在windows powershell下運行，但在windows上不能和sabaki連接。而將其打包為exe文件，會在每次運行的時候解壓一大堆文件在C盤，運行速度很慢，並且解壓完後有概率不會刪除，大量寫入對硬盤來說也是一種損壞，所以還在找其他的方法進行使用。如果找到了合適的方法會pull request，實在不行會把現在的方法放上去，希望其他人可以提供更好的方法。

**Comment by CGLemon** [comment]
那就拜託你了。謝謝！
