### ISSUE TITLE
Why are the features designed this way?

### ISSUE THREAD

**Issue by honglu2875** [CGLemon/pyDLGO#5]
https://github.com/CGLemon/pyDLGO/blob/c237ab644c8bd9f63a52c24e5a5595d1cab3d9c4/board.py#L440
Is the 18-layer feature design following some paper or trying to fit another library? The most direct thought would perhaps be just to output the past 16 boards, and flip the color depending on who is playing (so that the states are symmetric with respect to black/white). Wonder if there is any reason why the current one is used instead.

**Comment by CGLemon** [comment]
The design following the [Leela Zero](https://github.com/leela-zero/leela-zero). Here was the author said

```
There are 18 inputs to the first layer, instead of 17 as in the paper. The 
original AlphaGo Zero design has a slight imbalance in that it is easier for 
the black player to see the board edge (due to how padding works in neural 
networks).
```
