### ISSUE TITLE
Complete GTP with ids

### ISSUE THREAD

**Issue by HackYardo** [CGLemon/pyDLGO#6]
https://github.com/CGLemon/pyDLGO/blob/d330691cd2b2f47084aade56396528794fb7226a/gtp.py#L149-L154

It is not a complete GTP like this:
```
1 showboard
=1 
    A B C ...
19 
18
...
1

2 play b k10
=2

0 final_score
=0 7.5

5 quit
=5

```
Here. numbers before commands are ids.

**Comment by CGLemon** [comment]
Thanks.
I ignore it because there is no GTP app use that as far as i know.
I may fix it later, or feel free to send PR if you want to fix this issue.

**Comment by HackYardo** [comment]
Sorry, I am doing this(GTP) for my project, so I came to see your project, but we are using different languages and my project is not finished, I still want to do many things, like i18n, etc, so I will not participate in your project, but it looks like you are a teacher, perhaps your students can help you if you have enough spare time.

**Comment by kaorahi** [comment]
FYI: GTP ids are used in [Lizzie](https://github.com/featurecat/lizzie) and [LizGoban](https://github.com/kaorahi/lizgoban). The ids should be printed AFTER "=" like this.

~~~
1 name
=1 KataGo

2 quit
=2
~~~

**Comment by HackYardo** [comment]
Yeah, it is a standard of GTP, I had corrected my false text.

**Comment by CGLemon** [comment]
@kaorahi Thanks! I refer to the [GNU Go GTP](https://www.gnu.org/software/gnugo/gnugo_19.html) to implement the GTP id. I do not check it yet but I guess my implementation is correct?
